### ISSUE TITLE
React Basic demo

### ISSUE THREAD

**Issue by jensneuhaus** [pixelpassion/django-saas-boilerplate#23]
## ☝️What is it? Why do we need it?

It would be helpful to have some demo from React (and also Vue) working. I am not sure, if we should have it in the same repository or create a repository `react-boilerplate`?

Should we go for Websockets or not? Is it basic enough and will it be used in most upcoming projects? 
 
## 💭 Implementation details

- [ ] Have Sign up / Sign in / Password forget already working
- [ ] Have `users/me` API already working
- [ ] Have settings already working, e.g. `/settings/` API 
- [ ] Internationalization (usage of JSON or API, tbd)
- [ ] Make sure CORS works, even if it runs on a different domain
- [ ] Build process optimized (on Heroku or Circle CI?)
- [ ] app.json for Deployment of React app
- [ ] Should we go for Websockets? If yes, implementation of those

## 📋 Todos

- [ ] tbd
