### ISSUE TITLE
Support for Frontend: Sign up, Sign in, Password forget

### ISSUE THREAD

**Issue by jensneuhaus** [pixelpassion/django-saas-boilerplate#30]
Also check out issue #46 - both come together

### Sign in

![Boilerplate - Landing page   Sign in (Please redirect from Landing page to Sign in page)](https://user-images.githubusercontent.com/8494661/70989243-95abd780-20c3-11ea-8c2d-3ebb7e0813b4.png)

### Sign up

![Boilerplate - Sign up page](https://user-images.githubusercontent.com/8494661/70989248-96446e00-20c3-11ea-8e74-b0c056ab5aae.png)
![Boilerplate - Sign up page-2](https://user-images.githubusercontent.com/8494661/70989247-96446e00-20c3-11ea-88a5-6d4eda54f24e.png)

### Password forget

![Boilerplate - Password forget page (1_3)](https://user-images.githubusercontent.com/8494661/70989245-96446e00-20c3-11ea-9dcc-b7257efc4233.png)
![Boilerplate - Password forget page (1_3)-2](https://user-images.githubusercontent.com/8494661/70989244-95abd780-20c3-11ea-8692-20fdabb406d3.png)
![Boilerplate - Password forget page (3_3)](https://user-images.githubusercontent.com/8494661/70989246-96446e00-20c3-11ea-9099-3dccdec03e17.png)

## 📋 Todos

- [x] Checkout if https://django-rest-auth.readthedocs.io/en/latest/installation.html is the better tool for us as it brings a lot of more features
- [x] Sign in with Email + password
- [x] Sign up
  - [x] with First name + last name (please separate, image shows it wrong)
  - [x] with Email
  - [x] with password
  - [x] Send email activation link, email logic part of #46 + #36
- [x] Password forget logics, email logic part of #36
- [x] Password change logic for USer
