### ISSUE TITLE
Custom exception handling

### ISSUE THREAD

**Issue by jensneuhaus** [pixelpassion/django-saas-boilerplate#35]
## ☝️What is it? Why do we need it?

`django-rest-framework` works great but the exception handling is not as good because it mixes HTML responses (e.g. 404 or 500) with JSON responses

For the API the format should be consistent: 

```
{
   "message" : "This is a user message, we might show to the User"
   "error_code": "PASSWORD_TOO_INSECURE"
}
```

Please write a custom exception handler which we can use in all kind of projects, documentation on this is here: https://www.django-rest-framework.org/api-guide/exceptions/#custom-exception-handling

## 📋 Todos

- [ ] Read into my former (quick & dirty) solution: https://gist.github.com/jensneuhaus/f86ed013ff86292de0c8cd7dfb33185a  - I am happy if you have a better version of it
- [ ] Have a new custom exception service, which can e.g.
  - [ ] Only gives out JSON
  - [ ] Gives valid Status code responses, e.g. `400` on User errors; 500 on unknown errors, 404 on missing objects, 422 for potential Developer-errors and so on
  - [ ] Translate Django own HTML responses (e.g. for 500) into correct JSON
- [ ] Implement the custom_exception_handler also in the emails project and make sure, all errors from the API come correctly
