### ISSUE TITLE
Improved Email handling via Saasy

### ISSUE THREAD

**Issue by jensneuhaus** [pixelpassion/django-saas-boilerplate#36]
## ☝️What is it? Why do we need it?

We should use `sassy` to send emails. Please prepare the logic in the following way:

- If `SAASY_API_KEY` exists, we use Saasy; if not we use standard email behavior
- if we use Standard Django behavior, it translates the Mails with Context actually into Mails send by Django using a Template and we need a Email backend setup in the app we can use

## 📋 Todos

- [x] Implement an email backend to use `saasy`
  - [x] Make sure, that we could easily integrate this backend INTO `sassy` at one point
  - [x] Read [Django docs](https://docs.djangoproject.com/en/3.0/topics/email/#email-backends) and check how django-anymail handles APIs like Mailjet / Sendgrid
  - [x] if the `SAASY_API_KEY` exists, it should use our API to send default emails without template, using `context {  text:BODY, header:SUBJECT }, subject=SUBJECT`, etc. 
  - [x] If the API does not exist, it should give a message about the ENV being missed
- [x] Implement an EmailService for the usage of Templates + Context (like you did in DARE)
- [ ] Have standard emails
  - [ ] `simple-email-verification`
  - [ ] `simple-password-rest`
