### ISSUE TITLE
Add GDPR logics

### ISSUE THREAD

**Issue by jensneuhaus** [pixelpassion/django-saas-boilerplate#38]
### Inactive account handling

Delete an account with some informations to him, when the user was inactive for too long

### User deletes his account

The user decides to delete his account, we keep it for a few days

### Send all existing user informations to email

The user can ask to send all data

## 📋 Todos

- [x] Have all logics in an folder `gdpr`
- [x] Use env  `GDPR_ADMINISTRATOR_EMAIL`, default `None`
- [x] Use env `GDPR_SUPPORT_EMAIL`, default is `GDPR_ADMINISTRATOR_EMAIL`
- [x] Implement a  `daily_tasks` command
- [x] Inactive Account handling
   - [x] Use env `INACTIVE_ACCOUNT_DELETION_IN_WEEKS`, default `52`
  - [x] Make sure `INACTIVE_ACCOUNT_DELETION_IN_WEEKS` can be `None` - then there is no such logic
  - [x] Use env `INACTIVE_ACCOUNT_WARNING_IN_WEEKS`, default = `1,4` (it means, we remind 1 week and 4 week before it ends)
  - [x] Use env `INACTIVE_ACCOUNT_DELETION_BCC_EMAIL`, default `GDPR_ADMINISTRATOR_EMAIL`, do not send an BCC email if `None`
  - [x] Use env `INACTIVE_ACCOUNT_WARNING_BCC_EMAIL`, default `GDPR_ADMINISTRATOR_EMAIL`, do not send an BCC email if `None`
  - [x] Have some basic checks, that the ENV are correct. E.g. `52` + Warning `54`makes no sense.. or if it is set to None
  - [x] `send_warning_about_upcoming_account_deletion` Email (use BCC!)
  - [x] `send_warning_about_upcoming_account_deletion` handling as part of `daily_tasks` command; use BCC mail
  - [x] `send_inactive_account_was_deleted_email`  Email (use BCC!)
  - [x] `send_inactive_account_was_deleted_email` handling as part of `daily_tasks` command; use BCC mail
- [x] User deletes his Account handling
  - [x] Make sure the API works correctly, probably `DELETE /users/me`? 
  - [x] Soft delete the user, e.g. marking it `is_deleted`
  - [x] Use env `ACCOUNT_DELETION_RETENTION_IN_DAYS`, default `7`; if set to `0` the Account is deleted right away
  - [x] Use env `ACCOUNT_SCHEDULED_FOR_DELETION_BCC_EMAIL`, default `GDPR_ADMINISTRATOR_EMAIL`, do not send an BCC email if None
  - [x] Use env `ACCOUNT_DELETED_BCC_EMAIL`, default `GDPR_ADMINISTRATOR_EMAIL`, do not send an BCC email if None
  - [x] `send_account_scheduled_for_deletion_email`  Email (if not `0` days of retention)
  - [x] `send_account_scheduled_for_deletion_email` handling as part of `daily_tasks` command; use BCC mail
  - [x] `send_account_was_deleted_email`  Email
  - [x] `send_account_was_deleted_email` handling as part of `daily_tasks` command; use BCC mail
  - [x] Make sure, the account is reactivated, when the User logs back in; send `send_account_was_recovered_email`  Email then
