### ISSUE TITLE
Deployment + Status quo

### ISSUE THREAD

**Issue by jensneuhaus** [pixelpassion/django-saas-boilerplate#53]
## ☝️What is it? Why do we need it?

We want to make sure, the django-rest-boilerplate is working and can be used for upcoming projects

## 📋 Todos

- [x] Deploy using the `Deploy` button - fix problems in [app.json](https://devcenter.heroku.com/articles/app-json-schema)
- [x] If all runs, transfer the Heroku app to me / pixelpassion - we will use it as demo from then on
- [x] Improve + fix [README](https://github.com/pixelpassion/emails/blob/master/README.md)
  - [x] What steps are required to bring it to work locally?
  - [x] How can it be deployed? What ENVs are required and optional? 
- [x] Write down a detailed status quo in Slack - what is working, what should we think of and what needs to be done to use it in production? // Create issues if needed
- [x] Make sure CircleCI runs (talk to me if you need assistance!!)
- [x] How is the test coverage?  Are there tests cases which are missing?
