### ISSUE TITLE
Add a default web page

### ISSUE THREAD

**Issue by jensneuhaus** [pixelpassion/django-saas-boilerplate#57]
## ☝️What is it? Why do we need it?

We should add a default web page to show that all is working

![Startpage - Landing page](https://user-images.githubusercontent.com/8494661/76206611-a1a7c100-61fc-11ea-80c9-ab6573e85440.png)

### ENV Check

- Have a list of ENVs (can be hard coded)
   - Name of ENV
   - Title we show in front of it
   - Message we show
 
## 📋 Todos

- [x] Add a basic page which is shown when someone goes to the root
- [x] Add an ENV check to help people get started (described above)
- [x] Add links at the bottom
  - [x] django-saas-boilerplate.com/docs/ (hard coded as this will go to our DOMAIN!)
  - [x] <app instance url>/api/docs/ (or whatver the API Docs URL is)
  - [x] slack-invite.getautomagically.io/
